name: Django CI

on:
  push:
    paths:
      - 'messaging_app/**'
  pull_request:
    paths:
      - 'messaging_app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_Faithoverfear@1998_PASSWORD: Faithoverfear@1998
          MYSQL_DATABASE: alx_airbnb_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: Faithoverfear@1998
      MYSQL_PASSWORD: Faithoverfear@1998
      MYSQL_DATABASE: alx_airbnb_database

    defaults:
      run:
        working-directory: messaging_app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y mysql-client
        until mysqladmin ping -h "$MYSQL_HOST" --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run Django migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
