pipeline {
    agent any
    
    environment {
        PROJECT_DIR = 'messaging_app'
        PYTHON = 'python3'
        PIP = 'pip3'
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                git(
                    url: 'https://github.com/Gatlat-cs2023/alx-backend-python',
                    credentialsId: 'github-ssh-key', // Replace with your credential ID
                    branch: 'main',  // This was missing
                    changelog: true,
                    poll: true
                )
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh "${PIP} install --upgrade pip"
                    sh "${PIP} install -r requirements.txt"
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh "${PYTHON} -m pytest --junitxml=test-results.xml"
                }
            }
            post {
                always {
                    junit "${env.PROJECT_DIR}/test-results.xml"
                }
            }
        }
    }
}
