pipeline {
    agent any
    
    environment {
        PROJECT_DIR = 'messaging_app'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/alx-backend-python.git',
                    credentialsId: 'YOUR_GITHUB_CREDENTIALS_ID',  // Replace with your actual credentials ID
                    branch: 'main',
                    changelog: true,
                    poll: true
                )
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh 'python3 -m pip install --upgrade pip'
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir(env.PROJECT_DIR) {
                    sh 'pytest --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit "${env.PROJECT_DIR}/test-results.xml"
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed - cleaning up'
        }
    }
}
